### ISSUE TITLE
При какой частоте Attiny13A должна работать библиотека tinyLED?

### ISSUE THREAD

**Issue by xx1raven1xx** [GyverLibs/microLED#1]
Возник такой вопрос, при какой частоте Тиньки должна работать библиотека? При прошивке есть возможность выбрать частоту attiny13a, и на разной частоте соответственно разная скорость выполнения кода. Установлено MicroCore. Просто при подключении к тиньке одного светодиода для теста он не подает никаких признаков жизни, хотя блинк работает. (сам блинк который попадает ногой PB2 на вывод светодиода на arduino uno)

**Comment by GyverLibs** [comment]
Максимальная, 9.6 МГц вроде. Я тестировал, работает отлично
