### ISSUE TITLE
Platformio error compilation

### ISSUE THREAD

**Issue by GlebDen** [GyverLibs/microLED#5]
Приветствую.

При попытке скомпилировать тестовый скетч в Platformio получаю ошибки (см. скриншот):
![screenshot 391](https://github.com/user-attachments/assets/8e7c1783-da3b-4684-a60e-0ecb7515a981)

Что не так делаю?
Как исправить?

**Comment by GyverLibs** [comment]
Привет, очень просто, начать читать readme

> ## Совместимость
> Только AVR, ATmega и ATtiny
